[platformio]
src_dir = ./
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
upload_speed = 460800
monitor_speed = 115200
board_build.flash_mode = dio
lib_deps =
    mathieucarbou/ESP Async WebServer@3.0.6
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.4.0
build_src_filter =
  +<**/*.c>
  +<**/*.cpp>
  +<**/*.ino>
  -<./3rdparty/*>
  -<src/WebSockets.cpp>
  -<src/WebSocketsServer.cpp>

[env:esp32dev_nowifi]
extends = env:esp32dev
build_flags = -DENABLE_WIFI=0
lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.4.0
build_src_filter =
  ${env:esp32dev.build_src_filter}
  -<src/WebSockets.cpp>
  -<src/WebSocketsServer.cpp>
